version: '3'

services:

  cloud:
    image: model-transfer-service:v0.1
    container_name: mts-cloud
    restart: always
    volumes:
      - /app/storage/federated/cloud/outgoing:/app/outgoing
      - /app/storage/federated/local/incoming:/app/incoming
    environment:
      - "mts.folders.monitored=/app/outgoing"
      - "mts.folders.downloads=/app/incoming"
      - "mts.file.sender.id=cloud"
      - "mts.file.deleteUploads=true"
      - "kafka.bootstrapAddress=mts-kafka:9092"
      - "kafka.groupId=cloud"
      - "kafka.uploadsTopicName=teaching.federated_learning.aggregated_model"
      - "kafka.downloadsTopicName=teaching.federated_learning.client_models"
      - "crypto.algorithm=AES"
      - "crypto.aes.passwords={mts1: 'McoO!lMcjneowufUF23', mts2: 'IcjcdMLA23!ICOm2', mts3: 'jjioOOCLM932!jOC', cloud: 'IfjcoaO!ICJDMa214'}"
      - "crypto.aes.salts={mts1: 'dedc782d9130289c', mts2: '211C0A6AB767F21B', mts3: 'CB821D87B807A65A', cloud: '6068CCF5E6DFB752'}"